[project]
name = "hawk"
version = "0.1.0"
description = "hawk using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai-tools>=1.14.1",
    "crewai[litellm,tools]==1.14.1",
]

[project.scripts]
hawk = "hawk.main:run"
run_crew = "hawk.main:run"
train = "hawk.main:train"
replay = "hawk.main:replay"
test = "hawk.main:test"
run_with_trigger = "hawk.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
